### ISSUE TITLE
Missing Readme.md

### ISSUE THREAD

**Issue by benelot** [jgibson2/sea-thru#1]
Hello there!

Thanks for implementing and improving the sea-thru algorithm, it looks like really great work! I am trying to reproduce your results but it is rather hard to find out the exact steps. Your parameters refer to a Readme.md, but it is not part of the repository. Did you forget to push it? Otherwise, can you give me a quick run-down of how to use the code with the original dataset (I assume that is what it is compatible with) and how to train the monodepth network etc? That would be insanely helpful!

I intend to turn this into a python package and make it part of some open source image editing toolkit if possible, it seems people are interested to use it: https://github.com/darktable-org/darktable/issues/3434

Any help with this is highly appreciated!

Cheers

**Comment by jgibson2** [comment]
Hi! I have added a bit of a readme which I will improve over time. The monodepth network is pretrained, but any kind of depth map will work! For a general algorithm that doesn't require a depth map, however, I might recommend work such as https://arxiv.org/pdf/2004.05430.pdf, which will produce excellent results.

**Comment by benelot** [comment]
Thanks, I will look into it. I started to write my own readme as I was able to reproduce your results with the image from the report, but I am glad if you improved the documentation.

Thx for the additional literature.
