### ISSUE TITLE
Example image to reproduce your experiments

### ISSUE THREAD

**Issue by benelot** [jgibson2/sea-thru#2]
Hello again!

I think I understood how to run the code you wrote.

I run the seathru_mono_e2e.py with the --image parameter and let it run to recover an image for me. With the --output-graphs I get additional information on the estimated depth map and other things about the sea-thru method.

I get pretty bad results, as far as I see it is because the monodepth2 mono_1024x320 estimator fails to estimate a proper depthmap and subsequently neighborhood map and illumination map for it. The depthmap seems to turn out mostly flat except some parts on the left and right border that seems to be estimated a bit deeper than the rest. I have some ideas on how to fix this, but I want to be sure that the pipeline works if the same input is provided to it as you have provided.

I have seen an example image in your report, but unfortunately the image is missing from the repository, only the tex file is uploaded. I will try to get the image from the pdf, however, I hope you could provide me the name of the example image and of what dataset it was extracted. I think it would be nice if you commited your out folder with some samples in it such as  out/example_1/orig.jpg and out/example_1/depth_from_monodepth.png as well as the other files in the example_1 folder to make the report compile as such. This would strongly help me to reproduce your results and debug the problem for my own images.

Edit: It seems that using the extracted image from the report works quite well, although the contrast is a bit higher in my recovered image than in yours. That might be related to the parameters I used (default parameters) and not the ones that you reported in the report (if I remember well).

**Comment by federico-piazza** [comment]
Hi @benelot I found your comments on this. 

Were you able to successfully run this project? I am interested in knowing how to run this but I'm not a python dev nor data engineer so I'm not familiar at all with this area.

This project is missing a readme and reverse engineering for me on this area will be quite difficult.

I would really appreciate if you could give me few hints so I can test it on my scuba diving photos.

Thanks in advance!

**Comment by jgibson2** [comment]
I have added a bit of a README and pushed a fix that should improve your results.

I also added an example image and the resulting file. These were taken from the dataset I linked in the README. As far as the monodepth example goes... well it's not a perfect technique by any means ;) I'll play around with it and see if I can improve it.

**Comment by benelot** [comment]
@federico-piazza Hi! Yes, I was able to run the project but with mediocre results. The problem is not the Sea-Thru method, but the training of the monodepth2 is not appropriate to underwater scenes. At least for my pictures, I rarely get an appropriate depth map. I am looking into retraining monodepth2 on some additional underwater data to improve the depth map estimation.

@jgibson2 Thanks for implementing the method as such anyway, even if it is not yet perfect. There are many things to do to improve it, which is what I am interested in.

**Comment by jgibson2** [comment]
@benelot The method will work best with a visible floor and horizon, and multiple objects with straight-ish lines in the scene. Sadly getting these kinds of scenes is somewhat difficult. I might look into semi-supervised depth estimation techniques, which will require some input from you but might work better.
