### ISSUE TITLE
fatal: clone of 'git@github.com:nianticlabs/monodepth2.git' into submodule path '/path_to_cloned_repo' failed

### ISSUE THREAD

**Issue by jeffin07** [jgibson2/sea-thru#3]
@jgibson2 I was trying to test your implementation with a png file and I run  
`git submodule update --init --recursive`

And I get this error  
`fatal: clone of 'git@github.com:nianticlabs/monodepth2.git' into submodule path '/path_to_cloned_repo' failed`
`git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.`

Did you know what this might be? I'm using python3.8 PyTorch 1.6.0 with a virtual environment.

Also, it will be helpful if you include any of your test image samples :)

**Comment by jeffin07** [comment]
@jgibson2 I've changed .git/config file and now it's working  

I changed the line   
`[submodule "deps/monodepth2"]  
    active = true  
    url = git@github.com:nianticlabs/monodepth2.git  
`
to
`[submodule "deps/monodepth2"]  
        active = true  
        url = https://github.com/nianticlabs/monodepth2.git  
`

**Comment by jgibson2** [comment]
Ah good point -- I have mine set up as SSH by default. Mind submitting a PR?

**Comment by jeffin07** [comment]
@jgibson2  sure will submit a PR. I was waiting for your reply

**Comment by jgibson2** [comment]
https://github.com/jgibson2/sea-thru/pull/5
