### ISSUE TITLE
Why RAW format?

### ISSUE THREAD

**Issue by jeffin07** [jgibson2/sea-thru#4]
@jgibson2 why is the only "RAW" format is used in seatru.py? Any specific reason

**Comment by jgibson2** [comment]
That's just the format for the dataset from the paper, it could easily take a PNG though. Do you have a known depth map? If not you should be using the `seathru-mono-e2e.py` script that can take a PNG/JPEG image.

**Comment by jeffin07** [comment]
@jgibson2  okay. Yeah I have tried that I was just curious why do you gone with raw format. It would be helpful if there is an option to give other formats with known depth map 😊 just a suggestion

**Comment by jgibson2** [comment]
Closed: https://github.com/jgibson2/sea-thru/issues/6
